Repository linescaleGUI/linescaleGUI, pull requests merged in 2023-03, with the labels that each got.

#75 Toggle current and peak force group
  src/gui/mainwindow.cpp
Labels: bug

#71 Add packaging (cpack) and installing to folder
  .github/workflows/ci.yml
  BUILDING.md
  CMakeLists.txt
  README.md
  assets/app/linescaleGUI.desktop
  assets/app/linescaleGUI.png
  tests/CMakeLists.txt
  tools/cmake/CPackLinuxDeployQt.cmake.in
  tools/cmake/CPackMacDeployQt.cmake.in
  tools/cmake/packaging.cmake
Labels: CI/CD

#84 Enable unit change from UI
  src/deviceCommunication/commMaster.cpp
  src/deviceCommunication/commMaster.h
  src/gui/connectionWidget.cpp
  src/gui/connectionWidget.h
  src/gui/connectionWidget.ui
  src/gui/mainwindow.cpp
Labels: improvements

#94 Set `statusReading` flag
  src/gui/mainwindow.cpp
Labels: bug
